# 测试用例: 中风险 - 容器镜像版本升级
# 风险等级: medium
# 应用配置文件

apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-app-config
  namespace: production
data:
  app.yaml: |
    # 应用版本配置
    version: "v2.1.3"
    build_date: "2025-01-27"
    
    # 服务器配置
    server:
      port: 8080
      host: "0.0.0.0"
      timeout: 30s
      
    # 数据库配置
    database:
      host: "db.production.svc.cluster.local"
      port: 5432
      name: "microservice_db"
      ssl_mode: "require"
      connection_pool:
        max_connections: 20
        min_connections: 5
        
    # 缓存配置
    redis:
      host: "redis.production.svc.cluster.local"
      port: 6379
      db: 0
      timeout: 5s
      
    # 安全配置
    security:
      jwt_secret_key: "${JWT_SECRET}"
      session_timeout: 3600
      rate_limit:
        requests_per_minute: 100
        
    # 日志配置
    logging:
      level: "info"
      format: "json"
      output: "stdout"
      
    # 监控配置
    monitoring:
      metrics_enabled: true
      health_check_path: "/health"
      readiness_check_path: "/ready"
      
    # 新增功能配置
    features:
      security_patches: true
      performance_optimization: true
      new_api_version: "v2"
      
    # 环境变量
    environment: "production"
    debug: false