apiVersion: v1
kind: CDNConfiguration
metadata:
  name: main-website-cdn
  environment: production
spec:
  domain: www.example.com
  origins:
    - name: primary-origin
      domain: origin-elb-123456.ap-southeast-1.elb.amazonaws.com  # 从静态服务器改为ELB
      httpPort: 80
      httpsPort: 443
      weight: 100
      priority: 1
    - name: backup-origin
      domain: backup-origin.example.com
      httpPort: 80
      httpsPort: 443
      weight: 0  # 从50调整为0，禁用备用源站
      priority: 2
  http2: enabled  # 从disabled改为enabled
  ipv6: enabled
  https:
    enabled: true
    certificateId: cert-12345678
    http2: enabled
    tlsVersion: TLSv1.2
    forceRedirect: true  # 从false改为true，强制HTTPS跳转
  cacheSettings:
    queryStringConfig:
      behavior: whitelist  # 从all改为whitelist
      parameters:
        - id
        - token
        - version
    cookieConfig:
      behavior: none  # 从whitelist改为none，禁用Cookie缓存键
    headerConfig:
      behavior: whitelist
      headers:
        - Host
        - Accept-Encoding
  cacheBehaviors:
    - pathPattern: "/*.jpg"
      ttl: 86400  # 从3600增加到86400，图片缓存时间延长到1天
    - pathPattern: "/*.css"
      ttl: 604800  # 从86400增加到604800，CSS缓存时间延长到7天
    - pathPattern: "/*.js"
      ttl: 604800  # 从86400增加到604800，JS缓存时间延长到7天
    - pathPattern: "/api/*"
      ttl: 0  # 从60改为0，API请求不缓存
  waf:
    enabled: false  # 从true改为false，关闭WAF防护
  geoRestrictions:
    enabled: true
    restrictionType: blacklist
    countries:
      - RU
      - BY
      - KP
      - IR
      - SY  # 新增黑名单国家
  rateLimiting:
    enabled: false  # 从true改为false，关闭速率限制 