apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://host.docker.internal:8086
    database: risk_assessment
    user: admin
    password: admin123
    isDefault: true
    jsonData:
      version: Flux
      organization: risk-assessment
      defaultBucket: risk_data
      tlsSkipVerify: true
    secureJsonData:
      token: "admin-token"