apiVersion: apps/v1
kind: Deployment
metadata:
  name: lime-explain-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lime-explain-service
  template:
    metadata:
      labels:
        app: lime-explain-service
    spec:
      containers:
      - name: lime-explain-service
        image: lime-explain-service:latest
        ports:
        - containerPort: 8002
        env:
        - name: INFLUXDB_URL
          value: "http://influxdb:8086"
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: token
        - name: INFLUXDB_ORG
          value: "my-org"
        - name: INFLUXDB_BUCKET
          value: "risk_assessment"
---
apiVersion: v1
kind: Service
metadata:
  name: lime-explain-service
spec:
  selector:
    app: lime-explain-service
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP 